version: '3.8'

volumes:
  bball_league_api_local_postgres_data: {}
  bball_league_api_local_postgres_data_backups: {}
  static_volume:
  media_volume:


services:
  web:
    container_name: bball_league_api_web_1
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: ./compose/django/start # python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - ./app/:/usr/src/app/
      - ./compose/:/usr/src/app/compose
    expose:
      - 8000
    restart: always
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - bball_league_api_local_postgres_data:/var/lib/postgresql/data
      - bball_league_api_local_postgres_data_backups:/backups
    env_file:
      - ./app/.env
    restart: always
    