#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py create_default_superuser

python manage.py collectstatic --no-input --clear

gunicorn bball_league_api.wsgi:application --bind 0.0.0.0:8000 --timeout 30 --workers 2