# Generated by Django 4.2.4 on 2024-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_game_playoff_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
