# Generated by Django 4.2.4 on 2024-09-22 14:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_game_playoff_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="logo_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                default=api.models.get_default_season_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="api.season",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="season",
            field=models.ForeignKey(
                default=api.models.get_default_season_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="api.season",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                default=api.models.get_default_season_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="api.season",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "season")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name", "season")},
        ),
    ]
