# Generated by Django 4.2.4 on 2024-09-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_season_team_logo_url_game_season_player_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="hex_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
