# Generated by Django 4.2.4 on 2024-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_game_playoff_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="playoff_game",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QF1", "Quarterfinal 1"),
                    ("QF2", "Quarterfinal 2"),
                    ("QF3", "Quarterfinal 3"),
                    ("QF4", "Quarterfinal 4"),
                    ("SF1", "Semifinal 1"),
                    ("SF2", "Semifinal 2"),
                    ("TTB", "TTB"),
                    ("F", "Final"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
