# Generated by Django 4.2.4 on 2025-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_game_playoff_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatistics",
            name="efficiency",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="fouls_drawn",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="free_throw_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="minutes_played",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="plus_minus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="three_point_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="turnovers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="two_point_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
