# Generated by Django 4.2.4 on 2025-04-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_playerstatistics_efficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatistics",
            name="efficiency",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="playerstatistics",
            name="plus_minus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
